# Generated by Django 6.0.6 on 2026-06-19 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemgroup',
            name='code',
        ),
        migrations.RemoveField(
            model_name='shelf',
            name='code',
        ),
    ]
