# Generated by Django 6.0.6 on 2026-06-20 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_itemunit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemunit',
            name='factor',
            field=models.SmallIntegerField(default=1),
        ),
    ]
