# Generated by Django 6.0.6 on 2026-06-20 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_itemunit_factor'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemunit',
            name='min_selling_price',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='itemunit',
            name='sale_price',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
