# Generated by Django 6.0.6 on 2026-06-20 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_itemunit_min_selling_price_itemunit_sale_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='item_images/')),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='inventory.item')),
            ],
        ),
    ]
