# Generated by Django 6.0.6 on 2026-06-28 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('exchange_rate', models.DecimalField(decimal_places=4, default=1, max_digits=18)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('reference', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuotationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SalesExecutive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.ImageField(blank=True, null=True, upload_to='document_templates/headers/')),
                ('footer', models.ImageField(blank=True, null=True, upload_to='document_templates/footers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sale.customer')),
            ],
        ),
        migrations.CreateModel(
            name='SalesQuotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotation_no', models.CharField(max_length=30, unique=True)),
                ('quotation_date', models.DateField()),
                ('attention', models.CharField(blank=True, max_length=200)),
                ('pay_terms', models.CharField(blank=True, max_length=100)),
                ('delivery_place', models.CharField(blank=True, max_length=150)),
                ('exchange_rate', models.DecimalField(decimal_places=4, default=1, max_digits=18)),
                ('notes', models.TextField(blank=True)),
                ('gross_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('net_after_vat', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sale.currency')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sale.customer')),
                ('quotation_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sale.quotationtype')),
                ('sales_executive', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sale.salesexecutive')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=30, unique=True)),
                ('issue_date', models.DateField()),
                ('valid_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sale.quotationtype')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sale.salesquotation')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='SalesQuotationLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=500)),
                ('qty', models.PositiveSmallIntegerField(default=0)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('gross_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('vat_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('net_after_vat', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.item')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sale.salesquotation')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.itemunit')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
