# Generated by Django 6.0.6 on 2026-06-21 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0007_itemimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesQuotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quotation_no', models.CharField(max_length=30, unique=True)),
                ('quotation_type', models.CharField(choices=[('CASH', 'Cash'), ('CREDIT', 'Credit'), ('EXPORT', 'Export')], max_length=20)),
                ('customer', models.CharField(max_length=200)),
                ('quotation_date', models.DateField()),
                ('customer_reference', models.CharField(blank=True, max_length=50)),
                ('sales_executive', models.CharField(max_length=100)),
                ('attention', models.CharField(blank=True, max_length=200)),
                ('pay_terms', models.CharField(blank=True, max_length=100)),
                ('delivery_place', models.CharField(blank=True, max_length=150)),
                ('currency', models.CharField(max_length=10)),
                ('exchange_rate', models.DecimalField(decimal_places=6, default=1, max_digits=18)),
                ('notes', models.TextField(blank=True)),
                ('gross_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('net_after_vat', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='SalesQuotationLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=500)),
                ('qty', models.DecimalField(decimal_places=3, default=0, max_digits=18)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('gross_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('vat_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('net_after_vat', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.item')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sale.salesquotation')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.itemunit')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
