# Generated by Django 6.0.6 on 2026-06-21 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesquotation',
            name='quotation_type',
            field=models.CharField(max_length=20),
        ),
    ]
