# Generated by Django 6.0.6 on 2026-06-29 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0002_alter_salesquotation_quotation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesquotation',
            name='quotation_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sale.quotationtype'),
        ),
    ]
